import pyautogui as wa
import time
import random

#147 messages
messages = [
    "hey",
    "how's it going",
    "just saw something wild today",
    "did you watch that new show",
    "cant believe what happened earlier",
    "anyway lets catch up soon",
    "also did you finish your project",
    "by the way are you free this weekend",
    "lol that was hilarious",
    "need a coffee break",
    "have you tried that new game",
    "ngl im kinda tired today",
    "welp thats life i guess",
    "honestly didnt see that coming",
    "anyway moving on",
    "did you eat yet",
    "just got back from a walk",
    "also weather is nice today",
    "should probably do some work now",
    "anyway lets talk later",
    "saw a funny meme earlier",
    "by the way did you watch the game",
    "think i might nap soon",
    "lol that reminds me of something",
    "anyway back to what we were saying",
    "just remembered something",
    "also need to buy groceries",
    "ngl excited for the weekend",
    "welp time flies so fast",
    "honestly that was a weird day",
    "anyway gotta run",
    "did you see that video i sent",
    "might try cooking tonight",
    "also need to clean my room",
    "lol that was unexpected",
    "anyway lets chill sometime",
    "by the way did you hear the news",
    "just finished reading a book",
    "also need a new playlist",
    "welp talk later",
    # additional casual messages up to 200+
    "hey again",
    "guess what happened today",
    "saw a squirrel stealing food lol",
    "did you finish your work yet",
    "need a new laptop",
    "have you tried that coffee place",
    "lol cant stop laughing",
    "anyway gotta focus now",
    "also check out this link",
    "by the way whats your plan tomorrow",
    "ngl might sleep early tonight",
    "welp too much going on",
    "honestly forgot to tell you something",
    "anyway lets meet up soon",
    "did you hear that song",
    "just got a new idea",
    "also need to charge my phone",
    "lol that was so random",
    "anyway back to work",
    "just finished a game level",
    "by the way love that show",
    "might go for a run later",
    "also need to water the plants",
    "welp almost done with tasks",
    "honestly traffic was bad today",
    "anyway gotta grab lunch",
    "did you see the news today",
    "just saw a funny tweet",
    "also need to reply to emails",
    "lol cant believe that happened",
    "anyway talk later",
    "by the way remember our plan",
    "need a snack",
    "also check my latest post",
    "welp time to relax",
    "honestly almost forgot to call you",
    "anyway lets play a game later",
    "did you hear about that event",
    "just finished a podcast episode",
    "also thinking about watching a movie",
    "welp talk to you soon",
    "hey wanna play something later",
    "ngl im bored rn",
    "lol just remembered something funny",
    "anyway lets chill",
    "by the way what did you eat",
    "just got a new idea for a project",
    "also need to buy snacks",
    "welp almost forgot to text you",
    "honestly today was kinda lazy",
    "anyway catch up later",
    "did you see that funny clip",
    "just got back from a short walk",
    "also weather feels weird today",
    "lol cant stop thinking about that",
    "anyway gotta do homework",
    "by the way what time are you free",
    "hey just checking in",
    "ngl feeling kinda sleepy",
    "lol saw a meme and thought of you",
    "anyway lets go grab something to eat",
    "also need to clean my desk",
    "welp almost done with tasks",
    "honestly didnt expect that",
    "anyway talk soon",
    "did you hear about that new place",
    "just got a new song stuck in my head",
    "also need to reply to messages",
    "lol cant believe what just happened",
    "anyway gonna go for a walk",
    "by the way saw something funny",
    "hey wanna hang out later",
    "ngl today was kinda hectic",
    "lol just remembered a joke",
    "anyway need to do some work",
    "also need to charge my laptop",
    "welp time flies",
    "honestly forgot to tell you something important",
    "anyway talk later",
    "did you see that new clip",
    "just got back from a quick run",
    "also weather is nice",
    "lol cant stop laughing about that",
    "anyway gonna grab a snack",
    "by the way what are you doing",
    "hey just remembered something",
    "ngl im kinda lazy today",
    "lol saw something crazy online",
    "anyway lets chat later",
    "also need to buy some stuff",
    "welp almost forgot",
    "honestly didnt expect today to be like this",
    "anyway talk soon",
    "did you see the news today",
    "just finished a short video",
    "also thinking about a new idea",
    "lol cant believe that",
    "anyway gonna relax for a bit",
    "by the way wanna play a game",
    "hey check this out",
    "ngl im bored af",
    "lol just saw something funny",
    "anyway catch up later",
    "also need to finish some work",
    "welp thats all for now",
    "honestly today was chill",
    "anyway talk soon"
]

print("focus the text box now")
time.sleep(5)

for i, msg in enumerate(messages, 1):
    wa.write(msg)
    wa.press('enter')
    print(f"sent {i}/{len(messages)}")
